import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import AgroNavbar from "../components/AgroNavBar";
import AgroFooter from "../components/AgroFooter";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Amazonia | Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AgroNavbar />
        {children}
        <AgroFooter />
      </body>
    </html>
  );
}
